go_import_path: github.com/src-d/rovers
dist: trusty
sudo: required
os:
  - linux
  - osx
language: go
go:
  - 1.10.x
  - tip
matrix:
  fast_finish: true
  allow_failures:
    - go: tip
  exclude:
    - go: tip
      os: osx
env:
  global:
    - DBUSER=postgres
    - DBPASS=
    - CONFIG_GITHUB_TOKEN=$GITHUB_TOKEN
  matrix:
    - POSTGRESQL_VERSION=9.6 RABBITMQ_VERSION=any
cache:
  directories:
    - $HOME/Library/Caches/Homebrew
install:
  - make ci-install
before_script:
  - psql -c 'create database testing;' -U postgres
script:
  - make ci-script
jobs:
  include:
    - stage: deploy
      if: tag IS present
      script: skip
      services:
        - docker
      sudo: required
      go: 1.10.x
      before_deploy:
        - make packages
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: build/*.tar.gz
        skip_cleanup: true
      after_deploy:
        -  DOCKER_PUSH_LATEST=1 make docker-push
