dist: trusty
sudo: required
os:
  - linux
  - osx
osx_image: xcode9.3
language: go
go: 1.10.x
env:
  global:
    - DBUSER=postgres
    - DBPASS=
  matrix:
    - POSTGRESQL_VERSION=9.6 RABBITMQ_VERSION=any
cache:
  directories:
    - $HOME/Library/Caches/Homebrew
install:
  - make ci-install
before_script:
  - psql -c 'create database testing;' -U postgres
script:
  - make ci-script
jobs:
  include:
    - stage: deploy
      if: tag IS present
      services:
        - docker
      script:
        - make packages
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: build/*.tar.gz
        skip_cleanup: true
      after_deploy:
        -  DOCKER_PUSH_LATEST=1 make docker-push
