go_import_path: github.com/src-d/rovers
dist: trusty
sudo: false
os:
  - linux
  - osx
language: go
go:
  - 1.10.x
  - tip
matrix:
  fast_finish: true
  allow_failures:
    - go: tip
  exclude:
    - go: tip
      os: osx
env:
  - DBUSER=postgres DBPASS= CONFIG_GITHUB_TOKEN=$GITHUB_TOKEN
services:
  - postgresql
  - rabbitmq
addons:
  postgresql: "9.6"
cache:
  directories:
    - $HOME/Library/Caches/Homebrew
before_script:
  # https://github.com/travis-ci/travis-ci/issues/1875
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm -rf /usr/local/var/postgres; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then initdb /usr/local/var/postgres; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pg_ctl -D /usr/local/var/postgres start; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then createuser -s postgres; fi
  # Install RabbitMQ on OS X
  # Workaround for Travis's failure to install and start RabbitMQ on osx builds
  # Reference https://github.com/travis-ci/travis-ci/issues/5941
  # Copied from https://github.com/pika/pika/pull/740/files
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install rabbitmq;

      echo Starting RabbitMQ...;
      export PATH="${PATH}:/usr/local/sbin";
      sudo rabbitmq-server -detached;
    fi
  - psql -c 'create database testing;' -U postgres
script:
  - make test-coverage
  - make packages
jobs:
  include:
    - stage: deploy
      if: tag IS present
      script: skip
      services:
        - docker
      sudo: required
      go: 1.10.x
      before_deploy:
        - make packages
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: build/*.tar.gz
        skip_cleanup: true
      after_deploy:
        -  DOCKER_PUSH_LATEST=1 make docker-push
