go_import_path: github.com/src-d/rovers
dist: trusty
sudo: false
os: linux
language: go
go:
  - 1.10.x
  - tip
matrix:
  fast_finish: true
  allow_failures:
    - go: tip
env:
  - DBUSER=postgres DBPASS= CONFIG_GITHUB_TOKEN=$GITHUB_TOKEN
services:
  - postgresql
  - rabbitmq
addons:
  postgresql: "9.6"
before_script:
  - psql -c 'create database testing;' -U postgres
script:
  - make test-coverage
jobs:
  include:
    - stage: deploy
      script: skip
      services:
        - docker
      sudo: required
      go: 1.10.x
      script:
        - make packages
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: build/*.tar.gz
        skip_cleanup: true
        on:
          tags: true
      after_deploy:
        -  DOCKER_PUSH_LATEST=1 make docker-push
