language: go
#TODO: remove this
go_import_path: github.com/src-d/rovers

env:
  global:
  - GOLANG_PACKAGE=github.com/src-d/rovers
  - CONFIG_GITHUB_TOKEN=$GITHUB_TOKEN
  matrix:
  - GOLANG_IMAGE=golang:1.10-alpine

services:
  - docker

script:
  - make test-coverage

before_deploy:
  - make packages

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: build/*.tar.gz
  skip_cleanup: true
  on:
    tags: true

after_deploy:
  -  DOCKER_PUSH_LATEST=1 make docker-push
