version: '3.0'
services:
  postgres:
    image: postgres:10.3-alpine
    environment:
    - POSTGRES_DB=testing
    - POSTGRES_USER=testing
    - POSTGRES_PASSWORD=testing
  rabbit:
    image: rabbitmq:3.7-alpine
  go:
    image: ${GOLANG_IMAGE}
    entrypoint: ["go"]
    command: ["test", "-v", "./..."]
    volumes:
      - ".:/go/src/${GOLANG_PACKAGE}"
    links:
    - postgres
    - rabbit
    environment:
    - DBHOST=postgres
    - CONFIG_BROKER_URL=amqp://guest:guest@rabbit:5672/
    - CONFIG_GITHUB_TOKEN=${CONFIG_GITHUB_TOKEN}